#!/bin/sh


# $1 : name of container ( name in lxc-start with -n)
# $2 : net
# $3 : network flags, up or down
# $4 : network type, for example, veth
# $5 : value of lxc.network.veth.pair 

#ovs-vsctl --may-exist add-port $Bridge $5 tag=$VLANID
ovs-vsctl --may-exist add-br $Bridge
ovs-vsctl --if-exists del-port $Bridge $5
ovs-vsctl --may-exist add-port $Bridge $5 tag=$VLANID
ovs-vsctl --may-exist add-port $Bridge vxlan-$VLANID-$MasterIP -- set interface vxlan-$VLANID-$MasterIP type=vxlan options:remote_ip=$MasterIP options:key=$VLANID
